include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = QuorraPrefs

QuorraPrefs_FILES = QuorraPrefsRootListController.m
QuorraPrefs_FRAMEWORKS = UIKit
QuorraPrefs_PRIVATE_FRAMEWORKS = Preferences
QuorraPrefs_INSTALL_PATH = /Library/PreferenceBundles
QuorraPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
